[tool.poetry]
name = "readability-lxml"
version = ""
description = "fast html to text parser (article readability tool) with python 3 support"
authors = ["Yuri Baburov <burchik@gmail.com>"]
license = "Apache License 2.0"
readme = "README.md"
packages = [
    { include = "readability" },
]

[tool.poetry.dependencies]
python = ">=3.8.2,<3.14"
chardet = "^5.2.0"
cssselect = [
    { version = "" },
    { version = "" }
]
lxml = {extras = ["html-clean"], version = ""}
lxml-html-clean = {markers = "python_version < \"3.11\"", version = ""}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
